# Generated by Django 2.0 on 2019-10-30 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Electrician',
            fields=[
                ('aadhar_num', models.BigIntegerField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=50)),
                ('rfid_num', models.BigIntegerField(default=0)),
            ],
        ),
    ]
